bool Guns = false, FFAktif = false, sadecetabanca = false, bac = false, revive = false;
bool Ak47 = true, M4a4 = true, M4a1 = true, Awp = true;
bool Deagle = true, Usp = true, Glock = true, P2000 = true;
bool g_Gidilecekyerbelirten[MAXPLAYERS + 1] = false;
Handle g_gerisaytimer = null, g_gerisaytimerr = null;
int GeriSay = 0;
int g_WeaponParent = -1;
int DondurmaSure = 0, KapatmaSure = 0;
ConVar g_Yetkiliflag = null, g_Yetkiliflagg = null;
char GidilecekYer[32];